/*
 * USART_config.h
 *
 *  Created on: Feb 3, 2024
 *      Author: MAGIC
 */

#ifndef STM32F103C6_DRIVERS_MCAL_USART_USART_CONFIG_H_
#define STM32F103C6_DRIVERS_MCAL_USART_USART_CONFIG_H_



#endif /* STM32F103C6_DRIVERS_MCAL_USART_USART_CONFIG_H_ */
