/*
 * EEPROM_Private.h
 *
 *  Created on: ٢٥‏/٠٤‏/٢٠٢٤
 *      Author: MAGIC
 */

#ifndef STM32F103C6_DRIVERS_HAL_EEPROM_EEPROM_PRIVATE_H_
#define STM32F103C6_DRIVERS_HAL_EEPROM_EEPROM_PRIVATE_H_



#endif /* STM32F103C6_DRIVERS_HAL_EEPROM_EEPROM_PRIVATE_H_ */
