/*
 * EXTI&AFIO_config.h
 *
 *  Created on: ١٨‏/١٢‏/٢٠٢٣
 *      Author: MAGIC
 */

#ifndef STM32F103C6_DRIVERS_MCAL_EXTI_AND_AFIO_EXTI_AFIO_CONFIG_H_
#define STM32F103C6_DRIVERS_MCAL_EXTI_AND_AFIO_EXTI_AFIO_CONFIG_H_



#endif /* STM32F103C6_DRIVERS_MCAL_EXTI_AND_AFIO_EXTI_AFIO_CONFIG_H_ */
