/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
typedef unsigned int      unit32;
typedef volatile unit32  v_unit32;

#define RCC_BASE           0x40021000
#define PORTA_BASE         0x40021000
#define RCC_APB2ENR        *(volatile unit32*)(RCC_BASE+0x18)
#define GPIOA_CRH          *((volatile unit32*)PORTA_BASE+0x04)
#define GPIOA_ODR          *((volatile unit32*)PORTA_BASE+0x0C)
typedef union{
v_unit32 all_fields;
	struct {
v_unit32 reseved :13;
v_unit32 pin13:1;
}pin;
}R_ODR_T;
int main(void)
{
	volatile R_ODR_T *port=(R_ODR_T*)GPIOA_ODR;//casting

RCC_APB2ENR|=(1<<2);
GPIOA_CRH&=0XFF0FFFFF;
GPIOA_CRH|=0X00200000;
//port->pin.pin13=1;
while(1){
	GPIOA_ODR|=(1<<13);
	//port->pin.pin13=1;

	for(int i=0;i<500;i++);
		GPIOA_ODR&=~(1<<13);
		//port->pin.pin13=0;
		for(int i=0;i<500;i++);


}
return 0;
}
