#@copyrigth :ibrahim
CC=arm-none-eabi-
CFLAGS=-mcpu=cortex-m4 -gdwarf-2 -g
INCS=-I .
LIBS= 
SRC=$(wildcard *.c)
OBJ=$(SRC:.c=.o)
As=$(wildcard *.s)
AsOBJ=$(As:.s=.o)
Project_name=unit3_lap4_cortex_m4

all: $(Project_name).bin
	@echo "--------------build is done---------------------"

 %.o: %.c
	$(CC)gcc.exe -c $(INCS) $(CFLAGS) $< -o $@  
 
 $(Project_name).elf: $(OBJ) 
	$(CC)ld.exe -T linker_script.ld $(OBJ) $(AsOBJ) -o $(Project_name).elf -Map=Map_file.map
	cp $(Project_name).elf $(Project_name).axf
$(Project_name).bin:	$(Project_name).elf 
	 $(CC)objcopy.exe -O binary $< $@
clean:
	rm *bin *elf	
clean_all:
	rm *.bin *.elf *.o *.axf *.map